---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-hw7

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crole-hw7
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-hw7
roleRef:
  kind: ClusterRole
  name: crole-hw7
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sa-hw7
  namespace: default

