apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: otus-secret-store
  namespace: vault
spec:
#  retrySettings:
#    maxRetries: 5
#    retryInterval: "10s"
  provider:
    vault:
      namespace: "vault"
      server: "http://vault.vault:8200"
      path: "otus"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "otus"
          secretRef:
            name: "vault-auth-secret"
            key: "token"
#          serviceAccountRef:
#            name: "vault-auth"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otus-external-secret
  namespace: vault
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: "otus-secret-store"
  target:
    name: "otus-cred"
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "cred"

