promtail:
    namespace: monitoring
    tolerations:
        - key: node-role
          operator: Equal
          value: infra
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists

loki-distributed:
    loki:
      nodeSelector: { infraNode: 'true' }
      tolerations: [{ key: "node-role", operator: "Equal", value: "infra" }]
    ingester:
      nodeSelector: { infraNode: 'true' }
      tolerations: [{ key: "node-role", operator: "Equal", value: "infra" }]
    distributor:
      nodeSelector: { infraNode: 'true' }
      tolerations: [{ key: "node-role", operator: "Equal", value: "infra" }]
    querier:
      nodeSelector: { infraNode: 'true' }
      tolerations: [{ key: "node-role", operator: "Equal", value: "infra" }]
    queryFrontend:
      nodeSelector: { infraNode: 'true' }
      tolerations: [{ key: "node-role", operator: "Equal", value: "infra" }]
    gateway:
      nodeSelector: { infraNode: 'true' }
      tolerations: [{ key: "node-role", operator: "Equal", value: "infra" }]

